all: exercise3

.outputFolder:
	mkdir -p out

exercise1: .outputFolder
	clang -std=c++23 -lstdc++ -lm exercise1.cpp -Wall -Wextra -Werror -o out/exercise
	./out/exercise

exercise2: .outputFolder
	clang -std=c++23 -lstdc++ -lm exercise2.cpp -Wall -Wextra -Werror -o out/exercise
	./out/exercise

exercise3: .outputFolder
	clang -std=c++23 -lstdc++ -lm exercise3.cpp -Wall -Wextra -Werror -o out/exercise
	./out/exercise

exercise4: .outputFolder
	clang -std=c++23 -lstdc++ -lm exercise4.cpp -Wall -Wextra -Werror -o out/exercise
	./out/exercise

exercise5: .outputFolder
	clang -std=c++23 -lstdc++ -lm exercise5.cpp -Wall -Wextra -Werror -o out/exercise
	./out/exercise

exc2_templ: .outputFolder
	clang -std=c++23 -lstdc++ -lm exc2_templ.cpp -Wall -Wextra -Werror -o out/exercise
	./out/exercise